# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-04 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='\uc774\uba54\uc77c')),
                ('nickname', models.CharField(max_length=30, verbose_name='\ub2c9\ub124\uc784')),
                ('permission', models.CharField(choices=[('AT', '\uad11\uace0\uc8fc'), ('MB', '\uc77c\ubc18')], default='MB', max_length=2, verbose_name='\uad8c\ud55c')),
                ('certification_date', models.DateField(blank=True, default=None, null=True, verbose_name='\uc778\uc99d\uc77c')),
                ('is_certificated', models.BooleanField(default=False, verbose_name='\uc778\uc99d\uc5ec\ubd80')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
