# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 05:08
from __future__ import unicode_literals

import blog.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTimeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo_thumbnail', blog.fields.ThumbnailImageField(upload_to='static/blog/post/%Y/%m')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
