# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 06:42
from __future__ import unicode_literals

import blog.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20180430_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=blog.fields.ThumbnailImageField(default=1, upload_to='static/profile_image/%Y/%m'),
            preserve_default=False,
        ),
    ]
