# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 01:55
from __future__ import unicode_literals

import blog.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_photo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_thumbnail',
            field=blog.fields.ThumbnailImageField(upload_to='static/blog/post/%Y/%m'),
        ),
    ]
