# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180427_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='active',
        ),
    ]
